// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjzjjiqgbirclskjhcah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqempqaXFnYmlyY2xza2poY2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDEzNTcsImV4cCI6MjA1NDYxNzM1N30.5sTDOtHnty8Bd5EFqn6JNK7IiFUsb5jDEBgW7aYMADQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);